# Generated by Django 3.2.9 on 2022-04-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='date',
            new_name='datetime',
        ),
    ]
